# Generated by Django 6.0.3 on 2026-03-10 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='menu_name')),
                ('description', models.TextField(blank=True, verbose_name='menu_description')),
                ('level', models.IntegerField(default=0, verbose_name='menu_level')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='menu_url')),
                ('view', models.CharField(blank=True, max_length=100, verbose_name='menu_view')),
                ('view_param', models.CharField(blank=True, max_length=100, verbose_name='menu_view_param')),
                ('order_no', models.IntegerField(default=0, verbose_name='order_no')),
                ('display_flag', models.BooleanField(default=True, verbose_name='display_flag')),
                ('use_flag', models.BooleanField(default=True, verbose_name='use_flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='category.menu')),
                ('url_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_url_type', to='common.code', verbose_name='menu_url_type')),
            ],
            options={
                'ordering': ['order_no'],
            },
        ),
    ]
