# Generated by Django 6.0.3 on 2026-03-13 12:36

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_menu_lft_menu_rght_menu_tree_id_alter_menu_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='category.menu'),
        ),
    ]
