# Generated by Django 6.0.1 on 2026-02-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_commented',
            field=models.BooleanField(default=True),
        ),
    ]
